Repository AY2021S1-CS2103T-T13-2/tp, pull requests merged in 2020-10, with the labels that each got.

#84 Update UserGuide and Edit Find Message
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/flashcard/MultipleChoiceQuestion.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: type.Bug, type.Chore

#112 Add ability to go back and forth through past commands
  src/main/java/quickcache/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
Labels: type.Enhancement

#127 Branch add difficulty to flashcard
  src/main/java/quickcache/logic/commands/AddMultipleChoiceQuestionCommand.java
  src/main/java/quickcache/logic/commands/AddOpenEndedQuestionCommand.java
  src/main/java/quickcache/logic/commands/EditCommand.java
  src/main/java/quickcache/logic/parser/AddMultipleChoiceQuestionCommandParser.java
  src/main/java/quickcache/logic/parser/AddOpenEndedQuestionCommandParser.java
  src/main/java/quickcache/logic/parser/CliSyntax.java
  src/main/java/quickcache/logic/parser/EditCommandParser.java
  src/main/java/quickcache/logic/parser/ParserUtil.java
  src/main/java/quickcache/model/flashcard/Difficulties.java
  src/main/java/quickcache/model/flashcard/Difficulty.java
  src/main/java/quickcache/model/flashcard/Flashcard.java
  src/main/java/quickcache/model/util/SampleDataUtil.java
  src/main/java/quickcache/storage/JsonAdaptedQuickCache.java
  src/test/java/quickcache/model/flashcard/DifficultyTest.java
  src/test/java/quickcache/storage/StorageManagerTest.java
Labels: priority.High, type.Story

#132 Add export implementation docs
  docs/DeveloperGuide.md
  docs/diagrams/ExportActivityDiagram.puml
  docs/diagrams/ExportParserSequenceDiagram.puml
  docs/diagrams/ExportSequenceDiagram.puml
  docs/diagrams/TestParserSequenceDiagram.puml
  docs/diagrams/TestSequenceDiagram.puml
  docs/images/ExportActivityDiagram.png
  docs/images/ExportParserSequenceDiagram.png
  docs/images/ExportSequenceDiagram.png
  docs/images/TestParserSequenceDiagram.png
  docs/images/TestSequenceDiagram.png
Labels: documentation.DG

#140 Add and Refactor test code for storage
  src/main/java/quickcache/model/flashcard/Difficulty.java
  src/main/java/quickcache/storage/JsonAdaptedQuickCache.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/quickcache/storage/JsonAdaptedFlashcardTest.java
  src/test/java/quickcache/storage/JsonAdaptedQuickCacheTest.java
  src/test/java/quickcache/storage/JsonQuickCacheStorageTest.java
  src/test/java/quickcache/storage/JsonSerializableQuickCacheTest.java
  src/test/java/quickcache/storage/JsonUserPrefsStorageTest.java
  src/test/java/quickcache/storage/StorageManagerTest.java
  src/test/java/quickcache/testutil/TypicalFlashcards.java
Labels: priority.High

#154 Edit Difficulty to allow for empty input after PREFIX_DIFFICULTY
  src/main/java/quickcache/logic/commands/EditCommand.java
  src/main/java/quickcache/logic/parser/ParserUtil.java
  src/main/java/quickcache/model/flashcard/Difficulty.java
Labels: type.Bug

#158 Implement Difficulty into GUI
  src/main/java/quickcache/logic/commands/EditCommand.java
  src/main/java/quickcache/ui/FlashcardDisplay.java
Labels: type.Enhancement

#153 Add stats by tags command and update user docs
  docs/UserGuide.md
  docs/images/StatsIndexStep1.png
  docs/images/StatsIndexStep2.png
  docs/images/StatsIndexStep3.png
  docs/images/StatsTagsStep1.png
  docs/images/StatsTagsStep2.png
  src/main/java/quickcache/logic/commands/CommandResult.java
  src/main/java/quickcache/logic/commands/StatsCommand.java
  src/main/java/quickcache/logic/parser/StatsCommandParser.java
  src/test/java/quickcache/logic/commands/CommandTestUtil.java
  src/test/java/quickcache/logic/commands/StatsCommandTest.java
  src/test/java/quickcache/logic/parser/StatsCommandParserTest.java
Labels: documentation.UG, type.Story

#159 Add QuickCache intro and update UG
  docs/UserGuide.md
  docs/images/ExportStep1.png
  docs/images/ExportStep2.png
  docs/images/ExportStep3a.png
  docs/images/ExportStep3b.png
  docs/images/ExportStep3c.png
  docs/images/ImportStep1.png
  docs/images/ImportStep2.png
  docs/images/ImportStep3.png
  docs/images/ImportStep4.png
  docs/images/TestMCQStep2.png
  docs/images/TestMCQStep3.png
  docs/images/TestMCQStep4.png
  docs/images/TestOpenStep2.png
  docs/images/TestOpenStep3.png
  docs/images/TestStep1.png
Labels: documentation.UG

#162 Add TOC and edit saving QuickCache data section of UG
  docs/UserGuide.md
Labels: documentation.UG, priority.High

#168 Add a more welcoming welcome message, aims of guide and spaces
  docs/UserGuide.md
Labels: documentation.UG

#169 Edit "get started” information
  src/main/java/quickcache/model/util/SampleDataUtil.java
Labels: type.Story

#171 Update StorageClassDiagram and ModelClassDiagram
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: type.Chore
