Repository AY2021S1-CS2103T-T13-2/tp, pull requests merged in 2020-11, with the labels that each got.

#204 Fix helpMessage image not showing in UG
  docs/UserGuide.md
Labels: severity.Medium, type.Bug

#206 Fix answer normalizing prematurely
  src/main/java/quickcache/model/flashcard/Answer.java
Labels: type.Bug

#205 Edit sample questions
  src/main/java/quickcache/model/util/SampleDataUtil.java
Labels: severity.Low

#217 Edit UG (Intro, Tag and Difficulty functionalities)
  docs/UserGuide.md
Labels: documentation.UG

#218 Add clearer explanation for import and add missing exclamation to alert-danger
  docs/UserGuide.md
Labels: documentation.UG

#225 Update GUI colour DEEP_BLUE
  src/main/java/quickcache/ui/PieChartDisplay.java
  src/main/java/quickcache/ui/UiManager.java
  src/main/resources/view/DeepBlueTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PieChart.css
Labels: type.Enhancement

#212 Update PPP for Gilbert
  docs/AboutUs.md
  docs/team/gilbert.md
  docs/team/gilberttan19.md
Labels: documentation.PPP

#228 Bug fix: edit command parser
  src/main/java/quickcache/logic/parser/EditCommandParser.java
Labels: type.Bug

#231 Refactor remnant code
  src/main/java/quickcache/MainApp.java
  src/main/java/quickcache/logic/commands/AddMultipleChoiceQuestionCommand.java
  src/main/java/quickcache/logic/commands/AddOpenEndedQuestionCommand.java
  src/main/java/quickcache/logic/commands/ClearCommand.java
  src/main/java/quickcache/logic/commands/DeleteCommand.java
  src/main/java/quickcache/logic/commands/EditCommand.java
  src/main/java/quickcache/logic/commands/ExitCommand.java
  src/main/java/quickcache/logic/commands/ListCommand.java
  src/main/java/quickcache/model/Model.java
  src/main/java/quickcache/model/ModelManager.java
  src/main/java/quickcache/model/QuickCache.java
  src/main/java/quickcache/model/ReadOnlyQuickCache.java
  src/main/java/quickcache/model/flashcard/exceptions/DuplicateFlashcardException.java
  src/main/java/quickcache/storage/JsonQuickCacheStorage.java
  src/test/data/JsonQuickCacheStorageTest/invalidAndValidFlashcardQuickCache.json
  src/test/data/JsonQuickCacheStorageTest/invalidFlashcardQuickCache.json
  src/test/data/JsonQuickCacheStorageTest/notJsonFormatQuickCache.json
  src/test/data/JsonSerializableQuickCacheTest/duplicateFlashcardQuickCache.json
  src/test/data/JsonSerializableQuickCacheTest/invalidFlashcardQuickCache.json
  src/test/data/JsonSerializableQuickCacheTest/typicalFlashcardQuickCache.json
  src/test/java/quickcache/logic/commands/ClearStatsCommandTest.java
  src/test/java/quickcache/logic/commands/OpenCommandTest.java
  src/test/java/quickcache/logic/commands/StatsCommandTest.java
  src/test/java/quickcache/model/UserPrefsTest.java
  src/test/java/quickcache/storage/JsonQuickCacheStorageTest.java
  src/test/java/quickcache/storage/JsonSerializableQuickCacheTest.java
  src/test/java/quickcache/testutil/QuickCacheBuilder.java
  src/test/java/quickcache/testutil/TestUtil.java
Labels: type.Chore

#242 Fix MCQ answer to be case sensitive
  src/main/java/quickcache/model/flashcard/Answer.java
  src/main/java/quickcache/model/flashcard/OpenEndedQuestion.java
  src/test/data/JsonQuickCacheStorageTest/invalidAndValidFlashcardQuickCache.json
  src/test/data/JsonQuickCacheStorageTest/invalidFlashcardQuickCache.json
  src/test/data/JsonSerializableQuickCacheTest/typicalFlashcardQuickCache.json
  src/test/java/quickcache/model/flashcard/AnswerTest.java
Labels: type.Bug

#245 Update features section in DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteByTagParserSequenceDiagram.puml
  docs/diagrams/DeleteByTagSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/DeleteByTagParserSequenceDiagram.png
  docs/images/DeleteByTagSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/team/gilberttan19.md
  src/main/java/quickcache/logic/commands/EditCommand.java
Labels: documentation.DG

#247 Update use case for import and export
  docs/DeveloperGuide.md
Labels: documentation.DG

#244 Update PPP for Xingjian
  docs/AboutUs.md
  docs/team/chenxj98.md
  docs/team/xingjian.md
Labels: documentation.PPP

#251 Resolve multiple difficulty prefixes issue
  src/main/java/quickcache/commons/core/Messages.java
  src/main/java/quickcache/logic/parser/AddMultipleChoiceQuestionCommandParser.java
  src/main/java/quickcache/logic/parser/AddOpenEndedQuestionCommandParser.java
  src/test/java/quickcache/logic/commands/CommandTestUtil.java
  src/test/java/quickcache/logic/parser/AddMultipleChoiceQuestionCommandParserTest.java
  src/test/java/quickcache/logic/parser/AddOpenEndedQuestionCommandParserTest.java
Labels: type.Bug

#233 Add Use Case for Edit Command.
  docs/DeveloperGuide.md
Labels: documentation.DG

#254 Update ug
  docs/UserGuide.md
Labels: documentation.UG

#232 Update portfolio
  docs/team/gilberttan19.md
Labels: documentation.PPP

#257 Minor fixes to the UG
  docs/UserGuide.md
Labels: documentation.UG

#220 Update PPP for Josiah
  docs/AboutUs.md
  docs/team/josiah.md
  docs/team/josiahkhoo.md
Labels: documentation.PPP

#260 Update Gilbert's Portfolio
  docs/DeveloperGuide.md
  docs/team/gilberttan19.md
Labels: documentation.PPP

#246 Add joshua's ppp
  docs/AboutUs.md
  docs/team/joshtyf.md
  docs/team/joshua.md
Labels: documentation.PPP

#268 Fix out of bound index in test not showing an invalid command
  src/main/java/quickcache/logic/commands/TestCommand.java
  src/main/java/quickcache/model/flashcard/MultipleChoiceQuestion.java
  src/test/java/quickcache/logic/commands/TestCommandTest.java
Labels: type.Bug

#265 Improve Josiah's PPP
  docs/team/josiahkhoo.md
Labels: documentation.PPP

#272 Update gilbert PPP
  docs/team/gilberttan19.md
Labels: documentation.PPP

#253 Update DG
  docs/DeveloperGuide.md
Labels: documentation.DG

#274 Add instructions for manual testing
  docs/DeveloperGuide.md
Labels: documentation.DG, type.Chore

#278 Add activity diagrams for delete
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteByIndexActivityDiagram.puml
  docs/diagrams/DeleteByTagActivityDiagram.puml
  docs/images/DeleteByIndexActivityDiagram.png
  docs/images/DeleteByTagActivityDiagram.png
  docs/team/chenxj98.md
  docs/team/fh-30.md
Labels: documentation.DG

#275 Change activity diagram for add and addmcq command
  docs/DeveloperGuide.md
  docs/diagrams/AddMcqActivityDiagram.puml
  docs/diagrams/AddOpenEndedActivityDiagram.puml
  docs/images/AddMcqActivityDiagram.png
  docs/images/AddOpenEndedActivityDiagram.png
Labels: documentation.DG

#282 Add edit and find activity diagrams
  docs/DeveloperGuide.md
  docs/diagrams/EditActivityDiagram.puml
  docs/diagrams/FindActivityDiagram.puml
  docs/images/EditActivityDiagram.png
  docs/images/FindActivityDiagram.png
Labels: documentation.DG

#280 Add additional details to the activity diagrams
  docs/diagrams/AddMcqActivityDiagram.puml
  docs/diagrams/AddOpenEndedActivityDiagram.puml
  docs/diagrams/ClearStatsActivityDiagram.puml
  docs/diagrams/DeleteByIndexActivityDiagram.puml
  docs/diagrams/DeleteByTagActivityDiagram.puml
  docs/diagrams/ExportActivityDiagram.puml
  docs/diagrams/ImportActivityDiagram.puml
  docs/diagrams/StatsActivityDiagram.puml
  docs/diagrams/TestActivityDiagram.puml
  docs/images/AddMcqActivityDiagram.png
  docs/images/AddOpenEndedActivityDiagram.png
  docs/images/ClearStatsActivityDiagram.png
  docs/images/DeleteByIndexActivityDiagram.png
  docs/images/DeleteByTagActivityDiagram.png
  docs/images/ExportActivityDiagram.png
  docs/images/ImportActivityDiagram.png
  docs/images/StatsActivityDiagram.png
  docs/images/TestActivityDiagram.png
Labels: documentation.DG

#284 Add Open Flashcard Activity Diagram
  docs/DeveloperGuide.md
  docs/diagrams/OpenFlashcardActivityDiagram.puml
  docs/images/OpenFlashcardActivityDiagram.png
Labels: documentation.DG

#286 Fix UG instruction mistake
  docs/UserGuide.md
Labels: documentation.UG, type.FeatureFlaw

#287 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddMcqActivityDiagram.puml
  docs/diagrams/AddOpenEndedActivityDiagram.puml
Labels: documentation.DG

#289 Update Ui Class Diagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: documentation.DG

#290 Update josh's ppp
  docs/team/joshtyf.md
Labels: documentation.PPP

#288 Edit manual testing
  docs/DeveloperGuide.md
Labels: documentation.DG

#294 Add display by stats implementation and small tweaks
  docs/DeveloperGuide.md
  docs/diagrams/StatsByTagActivityDiagram.puml
  docs/diagrams/StatsByTagParserSequenceDiagram.puml
  docs/diagrams/StatsByTagSequenceDiagram.puml
  docs/images/StatsByTagActivityDiagram.png
  docs/images/StatsByTagParserSequenceDiagram.png
  docs/images/StatsByTagSequenceDiagram.png
Labels: documentation.DG

#293 Update dg
  docs/DeveloperGuide.md
Labels: documentation.DG

#292 Change person to flashcard
  docs/DeveloperGuide.md
  src/main/java/quickcache/model/flashcard/UniqueFlashcardList.java
Labels: documentation.DG

#295 Update UG
  docs/UserGuide.md
Labels: documentation.UG

#296 Update effort component in Dg
  docs/DeveloperGuide.md
Labels: documentation.DG

#297 Update Xingjian PPP
  docs/team/chenxj98.md
Labels: documentation.PPP

#299 Update josh's ppp
  docs/team/joshtyf.md
Labels: documentation.PPP

#300 Fix spacing issue
  docs/team/joshtyf.md
Labels: documentation.PPP
